### ISSUE TITLE
検索APIの準備

### ISSUE THREAD

**Issue by kzumu** [jphacks/SD_1804#8]
取得した画像から検索をして分類できると嬉しい

**Comment by kzumu** [comment]
検索に時間は掛けすぎず、デモで驚かせられるような認識の精度まで向上させたいな。

**Comment by tomatoaiu** [comment]
うんうん

**Comment by tomatoaiu** [comment]
日付の検索は工夫の余地がある
`query=2018/10/21`
だとurlがおかしくなるので不可
`query=2018-10-21`や`query=2018_10_21`で受け取る必要がある

**Comment by tomatoaiu** [comment]
時間も工夫の余地がある
`query=13:00`
のコロンがけっこう怪しい
以下のurlが考察していて参考になりそう
http://koseki.hatenablog.com/entry/20120212/uricolon

**Comment by kzumu** [comment]
検索はiOSの方だけで対応できたので、サーバは大丈夫です。
いろいろ調べてみてくれていて申し訳ないけど、これでいきましょう。

**Comment by tomatoaiu** [comment]
ありがとう！
